**Práctica 3: Estadística descriptiva básica**

La meta de la tercera práctica es obtener información estadística básica de los datos.

Carguemos el CSV resultante de la práctica anterior para comenzar.

Las columnas que tenemos suelen mezclar datos numéricos disponibles con textos, 
como por ejemplo las calificaciones que pueden ser 73, NP o NC. 

Mejor hagamos una columna aparte que contiene un número o un NaN, sin arruinar los datos originales.

In [ ]:
import pandas as pd
d = pd.read_csv("casos.csv")
d['CF1op'] = d['1ra']
d.CF1op.unique()

Sale lo siguiente:

In [ ]:
array([nan, '58', 'NP', '69', '61', '72', '73', '59', '16', '68', '85',
       '80', '84', '87', '54', '67', '50', '77', '70', '60', '51', '52',
       '4', '53', '56', '22', '71', '20', '78', '14', '66', '10', '21',
       '64', '62', '2', '28', '34', '40', '79', '26', '75', '46', '15',
       '63', '83', '36', '76', '74', '57', '19', '100', '47', '91', '95',
       '86', '90', '44', '49', '82', '25', '81', '94', '27', '65', '92',
       '55', '18', '24', '97', '89', '1', '43', '31', '8', '38', '88',
       '93', '0', '12', '11', '41', '32', '98'], dtype=object)

Hay que deshacernos de los NP y mejor ponerlos el mismo nan que indica que no son números y que además ocupan ser enteros y no strings los valores almacenados.

In [ ]:
from numpy import NaN
d['CF1op'] = d['CF1op'].replace('NP', NaN)
d.CF1op = [int(v) if str(v).isdigit() else NaN for v in d.CF1op]
d.CF1op.mean()

y así aprendimos que el promedio de las calificaciones (numéricas) de primera oportunidad es 62.68359375. 

El chiste es ahora ver qué valor da para los casos distintos que se tiene: 1ra, 2da y 3ra.

In [ ]:
for c in d.caso.unique():
    print(c, d.loc[d.caso == c]['CF1op'].mean())

In [ ]:
nan nan
2da 61.6346153846
3ra 54.5
1ra 79.5688405797

Pues, ahí no hay sorpresas. Los que pasan en primera oportunidad, pasan porque tienen mejores calificaciones.

Chequemos también para segunda oportunidad (ahí ya no aplicará el caso de 1ra):

In [ ]:
>>> d['CF2op'] = d['2da']
>>> d.CF2op.unique()
array([nan, '79', '66', '73', '71', '63', '78', '68', '74', 'NP', '70',
       '75', '76', '46', '65', '82', '77', '80', '67', '56', '72', '62'], dtype=object)
>>> d.CF2op = [int(v) if str(v).isdigit() else NaN for v in d.CF2op]
>>> d.CF2op.mean()
71.185714285714283
>>> for c in d.caso.unique():
...     print(c, d.loc[d.caso == c]['CF2op'].mean())
... 
nan nan
2da 73.7307692308
3ra 63.8333333333
1ra nan

Los que pasan, pasan. Los que no pasan, no pasan.

Viendo las puras calificaciones no vamos a aprender nada sobre por qué pasaron o reprobaron. 

Habrá que incluir las respuestas de las encuestas.

En la primera encuesta (ini), se pregunta lo siguiente:
* el programa educativo
* criterios de inscripción al grupo (horario, salón, profesor, otro)
* cómo le fue en el semestre anterior (pregunta abierta)
* qué significa el nombre de la unidad de aprendizaje (pregunta abierta)
* *cuántas horas semanales planea estudiar* (esto nos podría servir hoy)
* con cuáles técnicas planea estudiar (pregunta abierta, no le entra a estadística básica)
* *qué calificación espera obtener* (opción múltiple, lo podemos analizar hoy)
* en qué basa su estimación (pregunta abierta)
* *en cuál prepa estudió* (podemos intentar analizar esto hoy)
* *en qué semestre entró a la FIME* (también esto es analizable)
* *cuántos puntos obtuvo en el examen de ingreso* (esto también nos sirve hoy)
* *si tiene otros estudios posteriores a la prepa* (igual esto lo podemos analizar)

En la segunda encuesta (mcu), se pregunta lo siguiente:
* *promedio actual en la FIME* (a ver si nos sirve)
* cómo había obtenido información sobre su profe antes de inscribir
* cómo ha cambiado su impresión de su profesor durante el semestre
* qué significado le tiene el nombre de la unidad de aprendizaje en este momento
* *cuántas horas semanales ha estudiado para la unidad* (lo podemos analizar)
* *si sabe cuántos créditos vale la unidad de aprendizaje* (intentemos analizarlo)
* *si sabe cuántas horas de estudio corresponden a un crédito* (esto también)
* con cuáles técnicas ha estudiado para la unidad en cuestión
* cómo se preparó para el examen de medio curso (en sus propias palabras)
* cómo le fue en el examen de medio curso (en sus propias palabras)
* cómo se le hizo la dificultad del examen (en sus propias palabras)
* *qué calificación espera obtener de la unidad* (opción múltiple)
* en qué basa el estimado
* *si tiene un trabajo* (esto lo podemos analizar)
* *cuántas horas por semana trabaja*, si tiene un trabajo (esto también)

En la tercera encuesta (ord), se pregunta lo siguiente:
* cómo ha cambiado su impresión de su profesor durante el semestre
* qué significado le tiene el nombre de la unidad de aprendizaje en este momento
* *cuántas horas semanales ha estudiado para la unidad en la segunda mitad* (analizar)
* con cuáles técnicas ha estudiado para la unidad en cuestión
* *ha asistido asesorías en la facultad* (analizar)
* *cuántas veces a asistido asesorías* (analizar)
* qué temas consultó en asesorías y qué opina sobre ellas
* cómo se ha preparado para el examen ordinario
* cómo espera que le vaya en el examen ordinario
* *qué calificación espera obtener* (opción múltiple, analizar)
* en qué basa el estimado
* *si hay temas que ocupará reforzar en el futuro* (opción múltiple, analizable)
* *qué tipo de apoyo quisiera tener* (checkboxes, analizar)
* dónde y cuándo le gustaría que la facu organice apoyo
* *cuáles medios utilizaría para actividades de aprendizaje* (opción múltiple)
* *en cuáles temas en general necesita apoyo* (opción múltiple, analizable)

Además, cada encuesta permite que el alumno deje un mensaje para su profesor. 

Todas las respuestas abiertas de texto quedan fuera del alcance de esta práctica.
Vamos a regresar a su procesamiento en una práctica más adelante.

Ahora hay que identificar cuáles columnas en nuestro data frame corresponden a preguntas que podemos analizar con estadística descriptiva sencilla.

In [ ]:
>>> d.dtypes[10:20]
hrsEstudio_x       object
hrsComentario_x    object
tecnicas_x         object
califEsp_x         object
baseEst_x          object
prepa              object
ingreso            object
examenIng          object
otrosEstudios      object
mensaje_x          object
dtype: object
>>> d.dtypes[20:30]
promActual       object
profe            object
tiempo_y         object
grupo_y          object
prom             object
info             object
cambio_x         object
significado_y    object
hrsEstudio_y     object
comentarioHrs    object
dtype: object
>>> d.dtypes[30:40]
creditos       object
corr           object
tecnicas_y     object
prepMC         object
comoFue        object
opinionMC      object
califEsp_y     object
baseEst_y      object
cualTrabajo    object
hrsTrabajo     object
dtype: object
>>> d.dtypes[40:50]
mensaje_y          object
tiempo             object
grupo              object
cambio_y           object
significado        object
hrsEstudio         object
hrsComentario_y    object
tecnicas           object
asesorias          object
vecesAsesorias     object
dtype: object
>>> d.dtypes[50:]
asesoriasComentario     object
prepOrd                 object
comoVaya                object
califEsp                object
baseEst                 object
temas                   object
apoyo                   object
comoOrg                 object
medios                  object
temasGral               object
mensaje                 object
1ra                     object
2da                     object
caso                    object
CF1op                  float64
CF2op                  float64
dtype: object

In [ ]:
>>> d.PE.unique()
array(['IAS', 'IEA', 'IMA', 'IME', 'IMTC ', 'ITS', 'Manufactura',
       'Materiales', nan], dtype=object)
>>> d.hrsEstudio_x.unique()
array(['1', '5', '15', nan, '2.5', '3.5', '3', '4.5', '0.75', '2', '4',
       '1.5', '10', '6.5', '0', '6', '8', '0.5', '7',
       'Entre una y dos horas por semana',
       'Entre tres y cinco horas por semana', '12',
       'Menos de una hora a la semana', 'Más de cinco horas por semana',
       '1.75', '20', '1.25',
       'Depende de mi entendimiento y lo que me tarde haciendo las tareas.',
       '9', '21', '5.5', '14', '12.5', '25', '17.5', '13', '0.6', '7.5',
       'Las que necesite y pueda acomodar con el resto de horas que les tengo que dedicar a otras materias',
       'depende pero me gustaria practicar mas'], dtype=object)


Lo de horas de estudio se puede limpiar, 
aún cuando los alumnos que contestaron en papel escribieron respuestas verbales en lugar de indicar un número.

Lo de las prepas también es un desmadre que ocuparía limpieza manual, pero ya es mucho, 
por lo cual lo dejamos para otra ocasión.

In [ ]:
>>> d.prepa.unique()
array(['UMM', '20', '15 Madero', '23', '1', '1 Apodaca', '3',
       'CONALEP de Rio Bravo Tam', '7', 'Tecnica Medica', '15 Florida',
       '7 Puentes', '7 oriente', 'Cetis 101',
       'Timberview Highschool Manspere Texas', '23 Santa Catarina', '2',
       'Pablo Livas', '19', 'Prepa tecnica medica', '9', 'EIAO Guadalupe',
       '15 Madero Bachillerato Bilingue', '16', '8', '22',
       'Prepa técnica emiliano zapata', 'cecyte allende', 'cbta 250', nan,
       'EIAO', 'Emiliano Zapata', '17 en Cienega de Flores', '17', '18',
       '25', 'UANE', '7 Oriente', 'Universidad Alfonso Reyes', 'CEDETEC',
       '13', 'Instituto de educacion superior de Monterrey',
       'Pablo Livas Centro', 'CECyTE N.L.', '22 Linda Vista',
       'CONALEP Dr Carlos Canseco Gonzalez.',
       'Colegio de Bachilleres del Edo; de Verazcruz No.10',
       'Cetis No. 66', 'Agosto-diciembre 2016', 'Enero-junio 2015',
       'Agosto-diciembre 2017', 'EIAO Unidad San Nicolás', 'CONALEP',
       'CONALEP Ing Adrian Sada Treviño',
       'Preparatoria Tecnica General Emiliano Zapata',
       'EIAO especialidad programacion web', 'Enero-junio 2018',
       'Agosto-diciembre 2013', 'Agosto-dicibre',
       'Entré a la Pablo Livas y acabé en la Preparatoria 3', 'CBTis258',
       'Colegio Bicentenario de la Independecia',
       'Centro Universitario Educativo y Cultural', 'UDEM',
       'EIAO Churubusco', 'Paideia ', 'Enero-junio 2017', 'EIAO ',
       '1 Colegio Civil', 'Universidad Alfonso Reyes ', 'CETIS 133',
       'Col. Salvador Díaz Miron (Poza Rica;Veracruz)',
       'CONALEP DON JOSE HERNANDEZ MARTINEZ', 'CBTis 7',
       'Preparatoria Técnica Emiliano Zapata', 'Agosto-diciembre 2015',
       'Enero-junio 2016', 'CIDEB',
       'International School of Tegucigalpa Honduras. ',
       'Tec Milenio Las Torres', '5', 'CBTis 221',
       'Instituto Central Coahuila.', '12',
       'UAMVH (Valle Hermoso Tamaulipas)',
       'Instituto Universitario Anglo Español',
       'Unidad Academica Multidisciplinaria campus Valle Hermoso',
       'Preparatoria de la Universidad Autónoma de Zacatecas ',
       'Instituto Regiomontano Cumbres', 'UVM', 'Instituto Laurens',
       'CBTIS 187', '26', 'Preparatoria Técnica Médica',
       'Centro de Investigacion y Desarrollo de Educacion Bilingue',
       'preparatoria indpendencia', 'EIAO Linares', 'Pablo Livas Poniente',
       'cacytec fransico coss ramos', 'EIAO MTY 1', 'CBTis',
       'EIAO San Nicolás', 'EIAO MTY I',
       'Escuela Industiral y Preparatoria Técnica Pablo Livas Unidad Poniente',
       '15', 'CUM de Monterrey ', 'CBTIS #85 (Veracruz)',
       'Tecnologico de Monterrey', 'cecyte ', '6', 'COLMEX', 'CBtis #22',
       'Jose vasconcelos', 'Universidad Del Norte', 'Tec Milenio', '14',
       'IIES', 'UANL', 'Enero-junio 2014',
       'Centro de Investigación y Desarrollo en Educación Bilingüe',
       'Colegio de Bachilleres', 'CBTis #74', 'INSUCO',
       'Escuela Industrial y Preparatoria Tecnica Alvaro Obregon',
       'Cigorroa High School', 'Prepa Tecnica Pablo Livas Pte',
       'Dr. Leo Cigarroa High School', 'bachillerato en E.U.A',
       'Tec Milenio San Nicolas', 'UR', 'Tec Emiliano zapata',
       'cbtis 236 Cd victoria tamaulipas',
       'instituto americano de montemorelos', '4 Linares', 'COBACH 13',
       'Colegio Ignacio Zapata (Saltillo)', 'CBTis No.24 Cd Victoria.',
       'CIDEB ', 'Instituto América de Estudios Superiores', 'UR ',
       'Preparatoria 7 U.S.N. 1', 'CIBED', 'CBTIS#22',
       'Tec de Monterrey campus eugenio garza sada', '(',
       'Colgio de Bachilleres plantel 09 San Luis Potosi',
       'Agosto-diciembre 2012', 'Colegio Champal',
       'instituto mano amiga de monterrey',
       'Colegio Ignacio Zaragoza La Salle Saltillo', 'Luzac',
       '1 en línea (Bajos Recursos).', 'Agosto- Diciembre 2013',
       'IAES (Nuevo Laredo)', '7 San Nicolás 1',
       'Instituto Vicente Suarez.', 'INTERLINE (Cadereyta)',
       'Tecnológico de Monterrey Valle Alto.', 'EIAO 3 caminos',
       '7; por cuestiones de dinero y materias no pude continuar; después estudié en la preparatoria de Cruz Roja.',
       'Colegio Excelsior (Plan UANL)', 'Cetis No. 163',
       'Instituto Latino Americano.', 'Colegio Regiomontano Contry.',
       'Bachillerato Técnico de la UDEM', 'Cbtis 24 Cd. Victoria Tamps.',
       'Agosto-Diciembre 2013', 'Instituto Anglo Mexicano',
       'Tec Milenio Cumbres', '15 Florida Billingüe'], dtype=object)

Viendo las respuestas a en qué semestre ingresaron a la facultad, surge una preocupación: 
vienen mezcladas respuestas a esa pregunta con respuestas la pregunta *siguiente*...

Algo está mal en los CSV de entrada de las encuestas y vamos a tener que ver qué es antes de proceder. 

Además, inspeccionar las respuestas a mano en una hoja de cálculo permite limpiar las broncas de los horas de estudio que vienen en letra. Por ejemplo, si dice que estudiará entre tres y cinco horas por semana, le pongo un cuatro y se acabó el problema. Respuestas como "Las que necesite y pueda acomodar con el resto de horas que les tengo que dedicar a otras materias" las reemplazo con NA ya que no serán analizables de forma cuantitativa.
De hecho, mejor pongo una escala:
* Nada
* Entre 1 y 2 horas
* Entre 2 y 3 horas
* Entre 3 y 5 horas
* Más de 5 horas
Así queda analizable y limpio.

La bronca con las demás preguntas parace ser que se ha agregado una nueva pregunta en algún momento y esa respuesta no existe para los semestres anteriores a la agregación, por lo cual se brincan las celdas.
Habrá que insertar ahí una celda con NA para aquellos que contestaron la pregunta nueva, para sí alinear las respuestas de los demás. 

¡Ha! Es al revés. AD18 tiene una pregunta menos. 

De una vez, viendo que la hoja contiene celdas vacías, le pongo un NA en cada celda que no contiene dato.

Además conviene echar un vistazo de una vez a las otras dos tablas de encuestas, por si ahí pasa algo similar.

Efectivamenta pasa lo mismo en mc.csv y en ord.csv con AD18.

In [ ]:
>>> d.ingreso.unique()
array(['Enero-junio 2017', nan, 'Enero-junio 2016',
       'Agosto-diciembre 2016', 'Agosto-diciembre 2017',
       'Agosto-diciembre 2014', 'Agosto-diciembre 2015',
       'Enero-junio 2015', 'Enero-junio 2014',
       'segun me acuerdo que los puntos para tener un lugar en FIME en aquel tiempo era de 1500 puntos',
       'Recuerdo que el dia de los resultados estaba en la ultima pagina de los aceptados.',
       'Pase en el 2 intento',
       'No recuerdo el número pero fue más que suficiente para pasar ',
       'bueno', 'que habia sido aceptado', 'No me dieron el resultado ',
       '1480', 'Nosé la verdad', 'No lo se',
       'Solo recibi la confirmacion de aprobacion no solicite puntaje',
       'Recuerdo no salir tan bajo al puntaje estimado ', 'No recuerdo',
       ...

Con las correcciones en los archivos CSV, 
hay que rehacer lo que se hizo en la segunda práctica para actualizar los archivos:

In [ ]:
import pandas as pd
enc_ini = pd.read_csv("encuestas/ini.csv")
enc_mcu = pd.read_csv("encuestas/mc.csv")
enc_ord = pd.read_csv("encuestas/ord.csv")
cf = pd.read_csv("profes.csv", header=None)
enc_mcu['matr'] = [str(valor) for valor in enc_mcu['matr']]
cf.columns = ['profe', 'sem', 'matr', '1ra', '2da']
cf['matr'] = [str(valor) for valor in cf['matr']]
enc_ini['profe'] = ['elisa' if 'Elisa' in str(valor) else 'moi' if 'Moi' in str(valor) else 'NA' for valor in enc_ini['grupo']]
enc_mcu['profe'] = ['elisa' if 'Elisa' in str(valor) else 'moi' if 'Moi' in str(valor) else 'NA' for valor in enc_mcu['grupo']]
enc_ord['profe'] = ['elisa' if 'Elisa' in str(valor) else 'moi' if 'Moi' in str(valor) else 'NA' for valor in enc_ord['grupo']]
tmp = pd.merge(enc_ini, enc_mcu, how='outer', on=['profe', 'sem', 'matr'])
tmp2 = pd.merge(tmp, enc_ord, how='outer', on=['profe', 'sem', 'matr'])
d = pd.merge(tmp2, cf, how='outer', on=['profe', 'sem', 'matr'])
d.to_csv('datos.csv')
casos = []
for i in d.index:
    cf1ra = str(d['1ra'][i])
    cf2da = str(d['2da'][i])
    if cf1ra.isdigit() and int(cf1ra) >= 70:
        casos.append('1ra')
    elif cf2da.isdigit() and int(cf2da) >= 70:
        casos.append('2da')
    elif cf1ra.isdigit() and cf2da.isdigit():
        casos.append('3ra')
    else:
        casos.append('NA')
d['caso'] = casos
d.to_csv('casos.csv')

Mejor ponerlo en un archivo, digamos combina.py, para que sea fácil de repetirlo cuando se le hagan correcciones o agregaciones futuras a los archivos.

In [ ]:
>>> d.ingreso.unique()
array(['Agosto-diciembre 2014', 'Enero-junio 2015',
       'Agosto-diciembre 2017', 'Agosto-diciembre 2016',
       'Agosto-diciembre 2015', 'Enero-junio 2014', nan,
       'Enero-junio 2017', 'Enero-junio 2018', '2012', 'Enero-junio 2016',
       'Agosto-dicibre', 'Enero-Junio 2013', 'Agosto diciembre 2013', '|',
       'AGOSTO DICIEMBRE 2011', 'Ago-Dic 2011', 'Agosto-diciembre 2013',
       'Agosto-diciembre 2012', 'Agosto-Diciembre 2013',
       'Enero-Agosto 1995', 'enero-junio 2013', 'Agosto- Diciembre 2013',
       'Agosto 2011'], dtype=object)

Esto sigue siendo un desmadre, ahora porque la gente no sabe escribir diciembre. Vamos a limpiarlo esta vez dentro del mismo python.

In [ ]:
>>> d.ingreso = ["AD" + v[-2:] if "dic" in v else "EJ" + v[-2:] if "nero" in v else NaN for v in [str(v) for v in d.ingreso]]
>>> d.ingreso.unique()
array(['AD14', 'EJ15', 'AD17', 'AD16', 'AD15', 'EJ14', nan, 'EJ17', 'EJ18',
       'EJ16', 'ADre', 'EJ13', 'AD13', 'AD12', 'EJ95'], dtype=object)

Casi ya queda, salvo que el sujeto que no puso año. 
Lo reemplazamos por NaN.

In [ ]:
array(['AD14', 'EJ15', 'AD17', 'AD16', 'AD15', 'EJ14', nan, 'EJ17', 'EJ18',
       'EJ16', 'EJ13', 'AD13', 'AD12', 'EJ95'], dtype=object)

Hay una leyenda urbana que es diferente el desempeño de alumnos que entran en agosto y los que entran en enero. Vamos a ver si es cierto en estos datos.

In [ ]:
>>> d['inicio'] = ['enero' if 'EJ' in v else 'agosto' if 'AD' else NaN for v in [str(v) for v in d.ingreso]]
>>> d.inicio.unique()
array(['agosto', 'enero'], dtype=object)
>>> for sem in d.inicio.unique():
...     print(sem, d.loc[d.inicio == sem]['CF1op'].mean())
...     print(sem, d.loc[d.inicio == sem]['CF2op'].mean())
... 
agosto 65.2612359551
agosto 71.0263157895
enero 56.8012820513
enero 71.375

He, pinta que hay algo. 

Los de agosto tienen mejores resultados en primera oportunidad que los de enero, aunque en segunda oportunidad lucen los de enero ligeramente por encima de los de agosto. 

Habrá que revisitar este tema en prácticas futuras con pruebas estadísticas para ver si la diferencia es significativa.

¿Qué tal por programa educativo?

In [ ]:
>>> for car in d.PE.unique():
...     print(car, "primera", d.loc[d.PE == car]['CF1op'].mean())
...     print(car, "segunda", d.loc[d.PE == car]['CF2op'].mean())
... 
IMTC  primera 62.2540540541
IMTC  segunda 71.5
ITS primera 61.6347826087
ITS segunda 71.5714285714
IAS primera 54.1
IAS segunda 70.5416666667
Materiales primera 80.8
Materiales segunda 70.0
IMA primera 77.6666666667
IMA segunda nan
IEA primera 100.0
IEA segunda nan
nan primera nan
nan segunda nan
IME primera 88.0
IME segunda nan
Manufactura primera nan
Manufactura segunda nan

Como no hemos incorporado las calificaciones de todos los profes, hay muchas carreras para las cuales no tenemos información aún.

Pinta que o los de materiales sacan mejores resultados o la clase de Moisés es más fácil, ya que tienen calificaciones mayores. 

Además hay un espacio de sobra en IMTC. Eso es fácil de quitar: cada ocurrencia de " ," en los CSV se reemplaza con ",". Mejor hacerlo de una vez.

In [ ]:
sed 's/\ ,/,/g' ini.csv > tmp
mv tmp ini.csv
sed 's/\ ,/,/g' mc.csv > tmp
mv tmp mc.csv
sed 's/\ ,/,/g' ord.csv > tmp
mv tmp ord.csv
cd ..
python3 combina.py

Vamos a revisitar lo de horas de estudio, ahora más limpio:

In [ ]:
>>> d.hrsEstudio_x.unique()
array([nan, 'Entre 1 y 2 horas', 'Más de 5 horas', 'Entre 2 y 3 horas',
       'Entre 3 y 5 horas', 'Menos de una hora', 'Nada'], dtype=object)
>>> d.hrsEstudio_x.value_counts()
Entre 3 y 5 horas    258
Entre 1 y 2 horas    258
Entre 2 y 3 horas    143
Más de 5 horas       122
Menos de una hora     11
Nada                   2
Name: hrsEstudio_x, dtype: int64

Para iniciar, veremos si las frecuencias de selecciones de las opciones 
difieren entre los casos 1ra, 2da y 3ra.

In [ ]:
>>> for c in d.caso.unique():
...     print(c, "\n", d.loc[d.caso == c]['hrsEstudio_x'].value_counts())
... 
2da 
 Entre 3 y 5 horas    11
Entre 2 y 3 horas    10
Entre 1 y 2 horas    10
Más de 5 horas        8
Name: hrsEstudio_x, dtype: int64
nan 
 Series([], Name: hrsEstudio_x, dtype: int64)
1ra 
 Entre 3 y 5 horas    69
Entre 1 y 2 horas    67
Más de 5 horas       31
Entre 2 y 3 horas    28
Menos de una hora     4
Name: hrsEstudio_x, dtype: int64
3ra 
 Más de 5 horas       5
Entre 2 y 3 horas    5
Entre 3 y 5 horas    4
Entre 1 y 2 horas    1
Menos de una hora    1
Name: hrsEstudio_x, dtype: int64

Los conteos son difíciles de comparar ya que son diferentes cantidades de personas en cada caso. Mejor normalizarlos y deshacernos de los valores que existentes.

In [ ]:
>>> for c in d.caso.unique():
...     print(c)
...     print(d.loc[d.caso == c]['hrsEstudio_x'].value_counts(sort=False, normalize=True, dropna=True))
... 
2da
Entre 2 y 3 horas    0.256410
Entre 3 y 5 horas    0.282051
Más de 5 horas       0.205128
Entre 1 y 2 horas    0.256410
Name: hrsEstudio_x, dtype: float64
nan
Series([], Name: hrsEstudio_x, dtype: float64)
1ra
Menos de una hora    0.020101
Entre 2 y 3 horas    0.140704
Más de 5 horas       0.155779
Entre 1 y 2 horas    0.336683
Entre 3 y 5 horas    0.346734
Name: hrsEstudio_x, dtype: float64
3ra
Entre 2 y 3 horas    0.3125
Más de 5 horas       0.3125
Entre 1 y 2 horas    0.0625
Entre 3 y 5 horas    0.2500
Menos de una hora    0.0625
Name: hrsEstudio_x, dtype: float64

Pinta que los que pasan en primera dicen que estudian más.
Convendría graficar esto en prácticas futuras igual como aplicar pruebas estadísticas.

Para ver si afecta lo de contar con otros estudios, hay que limpiar un poco otra vez ya que las respuestas son así:

In [ ]:
       'En proceso de tecnico industrial en electricidad y electronica especializada',
       'N/A.',
       'Idioma ingles; idioma alemán; técnico en informática; técnico en mecatrónica',
       'Tecnica en software en proceso',
       'abandonados y es el estudio del idioma ingles',
       'Estoy estudienado ingles y alemán', 'Diplomado en automatización.'

Mejor hagamos una nueva columna que contenga False si no tienen otros estudios y True en otro caso, dejando NaN en aquellos que no respondieron.

Primero hay que revisar manualmente de qué formas responden que no tienen estudios:
* No
* no
* ninguno
* No tengo algún estudio relacionado
* No.
* ademas de FIME no
* No tengo
* etc.

Será más fácil limpiar esto a mano en la hoja de cálculo que intentar en python, ya que buscar por "no" daría muchos errores. Al mismo tiempo se pueden limpiar los cambios de facultad y los cambios de carrera.

In [ ]:
>>> for resp in d.otrosEstudios.unique():
...     if 'no' in str(resp):
...         print(resp)
... 
comence preparatoria tecnica en programacion pero solo estuve el primer semestre asi que nen realidad no lo cuento como conocimiento previo
no
estudie en sonora la misma carrera  estaba en 5to semestre y decidi cambiarme a NL para estudiar  intente revalidar pero fue como empezar desde primer semestre
ninguno
No ninguno
No tengo alguno.
Actualmente estudio Ingeniería en Tecnología de la Información en el CEU.
Curso de Coreano
ingles que no he terminado
Ademas de FIME no
Terminados son la secundaria y la primaria no tengo nada abandonado y lo que tengo en proceso es acabar el ingles en el Centro de Idiomas
Marketing Digital estoy estudiando un diplomado en linea ya que es en el área que yo me quiero especializar o algo relacionado con la tecnología
Idiomas. Francés e Italiano.
no.
Llevo 3 años y medio estudiando el idioma Coreano
Abandone la carrera de medico cirujano partero en tercer semestre
Cambie de carrera dentro de la FIME porque abandoné los estudios y no me di de baja estaba en la carrera de Ingeniería en Administración de Sistemas y cambié a la carrera de Ingeniería en Tecnología de Software
Inglés lo dejé en intermedio. Yanno lo estudio.
Ninguno
Estudié técnico en mantenimiento aeronáutico estudio idiomas (italiano e inglés)
Carrera trunca en Lic. Innovación Empresarial.
Ninguno pero si aprendi algunas cosas sobre sistemas
Tomé un curso de verano de Máquinas-Herramientas.
la preparatoria era técnica así que también soy técnico en informática hace un año termine un curso de ingles aunque aun no me siento muy seguro cuando hablo siento que me falta mas fluidez y en estos momentos estoy por acabar un diplomado en Java
Estudie un ano la carrera de Ing. en Tecnologias de la Informacion y Comunicacion
Un diplomado en Matricería y uno en PLC nivel 1.
no tengo
Solo la educación básica. Terminé un curso de Inglés y estoy llevando en proceso uno de Alemán
Tecnología de Monterrey hasta 3er semestre.

In [ ]:
>>> for est in d.otrosEstudiosClas.unique():
...     print(est)
...     print(d.loc[d.otrosEstudiosClas == est]['CF1op'].mean())
...     print(d.loc[d.otrosEstudiosClas == est]['CF2op'].mean())
... 
Cambio de carrera en la FIME
51.625
72.0
Cambio de ciudad
76.0
nan
Cambio de facultad en la UANL
67.3333333333
nan
Cambio de institución educativa
34.0
nan
Idiomas
64.8787878788
68.1666666667
nan
nan
nan
No
56.6461538462
67.6666666667
Otra carrera simultánea
nan
nan
Otro
66.4782608696
73.0
Técnico
52.6538461538
73.0
>>> print(d['CF1op'].mean())
62.68359375
>>> print(d['CF2op'].mean())
71.1857142857

Pinta que el tener carrera técnica es el peor caso en primera oportunidad,
y no tener estudios adicionales es el segundo peor. 

Los que cambiaron de carrera parecen estar peor que la población general,
mientras los que cambiaron de facultad están mejor.

Nuevamente será necesario aplicar pruebas estadísticas antes de saltar a conclusiones.

Procediendo ahora a la segunda encuesta, nos damos cuenta que las horas de estudio ocupan nuevamente ser limpiados a mano ambos para la segunda y para la tercera encuesta.

In [ ]:
>>> d.hrsEstudio_y.unique()
array([nan, '5', '1', '2', '10', '4', '8', '3', '1.5', '2.5', '50',
       '4 horas a la semana', '1 -2 hrs por semana.', '3 por semana',
       'Al menos una hora.', '0.5', '6', 'Entre 1 hora o hora y media',
       '1 hora', '4 hrs', '5-7', 'dos horas', '24', '28', '4 hrs.',
       'solamente las horas clase que me toca', '0', '7', '70', '4 horas',
       '14', '13.5', '20', '9', '1hora', '6 horas', '15', '2 horas',
       'No lo e hecho', '25', '35', '12', '5 horas', '3-4', '4.25',
       '1 casi 2', '7 horas', '5.5', '4.5', '3.5', '1 o 2', '30 mins.',
       '3 horas', '1 hora a la semana', '5 hrs',
       '2 horas muy pocas la verdad', 'Aproximadamente 1 hora',
       '1 hora al día entre semana', '30 minutos', '2 horas mas clases',
       'De 2 a 3', '2 horas.',
       'Muy poco, 2 horas a la semana tal vez por poco tiempo gracias al trabajo.',
       '2 hrs por semana', '22', 'una hora', '0.45', '2 Horas', '11',
       '0.75', '30'], dtype=object)
>>> d.hrsEstudio.unique()
array([nan, '3', '1', '5.5', '14', '50', '3.5', '4 horas', '5', '2',
       '2hrs', '2.5', '4', '2 horas', '3-4', '1 hora', '1.5', '0.75', '28',
       '38', '6', '1 hora y media',
       'unas 2 o 3 por semana por tarea y PIA y laboratorio', '0',
       '12 horas.',
       'Bastantes, sobre todo al final del semestre, si llegué a las 50 horas por semana.',
       '10', 'Solo cuando estudio para los exámenes', '9', '8', '7',
       '1.24', '3 a la semana', '15', '0.5', '3 horas maxico', '30',
       '3 horas', '5 horas', '4.5', '12', '3 o 4', 'Mas de 10', '4-5',
       'una hora y media o dos', '10 horas', '1 por seman',
       '1 hr por semana', 'de 2 a 4', '8 hrs', '2 a 3 horas',
       'Una hora por semana', 'le eh dedicado como 3 horas',
       '50 horas aproximadamente', '2horas', '2 horas min', '2 o 3 horas',
       '1 hora.', '1 a 2', '2 hrs', '80', '1-2', '20',
       '2 horas, aproximadamente', '1:30 hrs', 'de 4 a 6 horas por semana',
       '35', '3 horas de cada lunes.', '5-6 horas',
       'Aproximadamente 4-6 hrs', '3 de clase más 3 de tarea', '4 a 5',
       '5 hrs', '8.5', '3 - 4 horas.'], dtype=object)

In [ ]:
>>> for hrs in ['', '_x', '_y']:
...     variante = 'hrsEstudio' + hrs
...     print(variante)
...     for c in d.caso.unique():
...         print(c, "\n", d.loc[d.caso == c][variante].value_counts(sort=False, normalize=True, dropna=True))
... 
hrsEstudio
nan 
 Series([], Name: hrsEstudio, dtype: float64)
1ra 
 Nada                        0.038251
Más de cinco horas          0.103825
Menos de una hora           0.021858
Entre una y dos horas       0.464481
Entre tres y cinco horas    0.185792
Entre dos y tres horas      0.185792
Name: hrsEstudio, dtype: float64
2da 
 Entre tres y cinco horas    0.21875
Entre dos y tres horas      0.25000
Entre una y dos horas       0.43750
Más de cinco horas          0.09375
Name: hrsEstudio, dtype: float64
3ra 
 Entre dos y tres horas      0.250
Entre una y dos horas       0.375
Entre tres y cinco horas    0.375
Name: hrsEstudio, dtype: float64
hrsEstudio_x
nan 
 Series([], Name: hrsEstudio_x, dtype: float64)
1ra 
 Más de 5 horas       0.155779
Menos de una hora    0.020101
Entre 1 y 2 horas    0.336683
Entre 3 y 5 horas    0.346734
Entre 2 y 3 horas    0.140704
Name: hrsEstudio_x, dtype: float64
2da 
 Entre 1 y 2 horas    0.256410
Más de 5 horas       0.205128
Entre 2 y 3 horas    0.256410
Entre 3 y 5 horas    0.282051
Name: hrsEstudio_x, dtype: float64
3ra 
 Entre 1 y 2 horas    0.0625
Más de 5 horas       0.3125
Entre 2 y 3 horas    0.3125
Menos de una hora    0.0625
Entre 3 y 5 horas    0.2500
Name: hrsEstudio_x, dtype: float64
hrsEstudio_y
nan 
 Series([], Name: hrsEstudio_y, dtype: float64)
1ra 
 Más de cinco horas          0.104478
Nada                        0.039801
Una hora o menos            0.218905
Entre una y dos horas       0.273632
Entre tres y cinco horas    0.164179
Entre dos y tres horas      0.199005
Name: hrsEstudio_y, dtype: float64
2da 
 Entre tres y cinco horas    0.117647
Nada                        0.029412
Entre dos y tres horas      0.264706
Una hora o menos            0.264706
Más de cinco horas          0.088235
Entre una y dos horas       0.235294
Name: hrsEstudio_y, dtype: float64
3ra 
 Entre tres y cinco horas    0.153846
Una hora o menos            0.230769
Entre dos y tres horas      0.076923
Entre una y dos horas       0.461538
Más de cinco horas          0.076923
Name: hrsEstudio_y, dtype: float64

Ahora lo latoso es estar recordando o adivinando cuál es la algo_x y cuál es la algo_y...
Mejor modifiquemos el python que crea el CSV de entrada para liberarnos de esa carga cognitiva:

In [ ]:
python3 combina.py
head -n 1 casos.csv | tr , '\n' 

sem
tiempo_ini
grupo_ini
matr
PE
criterios
semAnt
significado_ini
hrsEstudio_ini
hrsComentario
tecnicas_ini
califEsp_ini
baseEst_ini
prepa
ingreso
examenIng
otrosEstudios
otrosEstudiosClas
mensaje_ini
promActual
profe
tiempo_mcu
grupo_mcu
prom
info
cambio
significado_mcu
hrsEstudio_mcu
comentarioHrs
creditos
corr
tecnicas_mcu
prepMC
comoFue
opinionMC
califEsp_mcu
baseEst_mcu
cualTrabajo
hrsTrabajo
mensaje_mcu
tiempo
grupo
cambio_ord
significado
hrsEstudio
hrsComentario_ord
tecnicas
asesorias
vecesAsesorias
asesoriasComentario
prepOrd
comoVaya
califEsp
baseEst
temas
apoyo
comoOrg
medios
temasGral
mensaje
1ra
2da
caso
head -n 1 casos.csv | tr , '\n' | grep hrs
hrsEstudio_ini
hrsComentario
hrsEstudio_mcu
hrsTrabajo
hrsEstudio
hrsComentario_ord

Ya se acabó la pinche lucha:

In [ ]:
>>> for hrs in ['_ini', '_mcu', '']: # el que no tiene nada es el ordinario                                                                    
...     variante = 'hrsEstudio' + hrs
...     print(variante)
...     for c in d.caso.unique():
...         print(c, "\n", d.loc[d.caso == c][variante].value_counts(sort=False, normalize=True, dropna=True))
... 
hrsEstudio_ini
nan 
 Series([], Name: hrsEstudio_ini, dtype: float64)
1ra 
 Más de 5 horas       0.155779
Menos de una hora    0.020101
Entre 1 y 2 horas    0.336683
Entre 3 y 5 horas    0.346734
Entre 2 y 3 horas    0.140704
Name: hrsEstudio_ini, dtype: float64
2da 
 Entre 1 y 2 horas    0.256410
Más de 5 horas       0.205128
Entre 2 y 3 horas    0.256410
Entre 3 y 5 horas    0.282051
Name: hrsEstudio_ini, dtype: float64
3ra 
 Entre 1 y 2 horas    0.0625
Más de 5 horas       0.3125
Entre 2 y 3 horas    0.3125
Menos de una hora    0.0625
Entre 3 y 5 horas    0.2500
Name: hrsEstudio_ini, dtype: float64
hrsEstudio_mcu
nan 
 Series([], Name: hrsEstudio_mcu, dtype: float64)
1ra 
 Más de cinco horas          0.104478
Nada                        0.039801
Una hora o menos            0.218905
Entre una y dos horas       0.273632
Entre tres y cinco horas    0.164179
Entre dos y tres horas      0.199005
Name: hrsEstudio_mcu, dtype: float64
2da 
 Entre tres y cinco horas    0.117647
Nada                        0.029412
Entre dos y tres horas      0.264706
Una hora o menos            0.264706
Más de cinco horas          0.088235
Entre una y dos horas       0.235294
Name: hrsEstudio_mcu, dtype: float64
3ra 
 Entre tres y cinco horas    0.153846
Una hora o menos            0.230769
Entre dos y tres horas      0.076923
Entre una y dos horas       0.461538
Más de cinco horas          0.076923
Name: hrsEstudio_mcu, dtype: float64
hrsEstudio
nan 
 Series([], Name: hrsEstudio, dtype: float64)
1ra 
 Nada                        0.038251
Más de cinco horas          0.103825
Menos de una hora           0.021858
Entre una y dos horas       0.464481
Entre tres y cinco horas    0.185792
Entre dos y tres horas      0.185792
Name: hrsEstudio, dtype: float64
2da 
 Entre tres y cinco horas    0.21875
Entre dos y tres horas      0.25000
Entre una y dos horas       0.43750
Más de cinco horas          0.09375
Name: hrsEstudio, dtype: float64
3ra 
 Entre dos y tres horas      0.250
Entre una y dos horas       0.375
Entre tres y cinco horas    0.375
Name: hrsEstudio, dtype: float64

A ver... Esto también habrá que graficarlo para facilitar sacar conclusiones.
Será hasta una práctica futura entonces.

¿Que más ibamos checar? Por lo menos lo de sí o no trabajan además de estudiar.

In [ ]:
      'Me encuentro en un grupo de trabajo de esta misma facultad llamado FIME 3D desde hace un año.',
       '-', 'no tengo', 'No cuento con uno',
       'Staff en salón de fiestas infantiles', 'Trabajao en una empresa',
       'No tengo.', 'Plaza comercial ',
       'Cinépolis, pero planeó salirme en estos días ',

Pinta a que nuevamente será necesario una limpieza manual.
Mejor agregar una nueva columna "tieneTrabajo" en mc.csv en vez de modificar las respuestas.
Les pongo "Tiene" si o dijeron en qué trabajan o indicaron cuántas horas trabajan.
Les pongo "No tiene" si dijeron que no trabajan.
Les pongo "NA" si contestaron ni a la pregunta sobre en qué trabajan ni a la pregunta de cuántas horas trabajan.

In [ ]:
>>> d.tieneTrabajo.value_counts()
Tiene       249
No tiene     85
Name: tieneTrabajo, dtype: int64
        >>> for tt in d.tieneTrabajo.unique():
...     print(tt, "trabajo")
...     print(d.loc[d.tieneTrabajo == tt]['CF1op'].mean())
...     print(d.loc[d.tieneTrabajo == tt]['CF2op'].mean())
... 
nan trabajo
nan
nan
Tiene trabajo
67.7941176471
70.4
No tiene trabajo
73.171875
71.0

Pinta que los que *no* trabajan sacan mejores calificaciones y hasta pasan en primera, 
mientras los que sí trabajan suelen tronar.
Otra cosa para examinar con pruebas estadísticas en prácticas futuras.

También conviene checar si las horas trabajadas afecten en algo. 

In [ ]:
>>> d.hrsTrabajo.unique()
array([nan, 'Entre 20 y 40 horas', 'No tengo un trabajo',
       'Más de 40 horas', 'Menos de 10 horas', 'Entre 10 y 20 horas'], dtype=object)
>>> d.hrsTrabajo.val
d.hrsTrabajo.valid(        d.hrsTrabajo.value_counts( d.hrsTrabajo.values       
>>> d.hrsTrabajo.val
d.hrsTrabajo.valid(        d.hrsTrabajo.value_counts( d.hrsTrabajo.values       
>>> d.hrsTrabajo.value_counts()
No tengo un trabajo    74
Más de 40 horas        70
Entre 20 y 40 horas    68
Entre 10 y 20 horas    55
Menos de 10 horas      46
Name: hrsTrabajo, dtype: int64
                                                     >>> for hrs in d.hrsTrabajo.unique():
...     print(hrs)
...     print(d.loc[d.hrsTrabajo == hrs]['CF1op'].mean())
...     print(d.loc[d.hrsTrabajo == hrs]['CF2op'].mean())
... 
nan
nan
nan
Entre 20 y 40 horas
69.1666666667
68.0
No tengo un trabajo
72.6730769231
70.0
Más de 40 horas
66.2641509434
71.375
Menos de 10 horas
72.4838709677
72.7142857143
Entre 10 y 20 horas
62.2580645161
69.25

Los que trabajan poco (menos de diez horas o nada) se ven parejos, 
mientras los que 10-20 horas tienen las calificaciones más bajas en primera oportunidad.
Los de 20-40 salen mejor que los de 10-20 y también mejor que los de 40+.

Probemos la correlación entre horas trabajadas y la calificación de primera oportunidad
con la siguiente codificación:
* 0 = No tengo un trabajo
* 5 = Menos de 10 horas
* 15 = Entre 10 y 20 horas
* 30 = Entre 20 y 40 horas
* 50 = Más de 40 horas

In [ ]:
>>> hrs = {"No tengo un trabajo": 0, \
...        "Menos de 10 horas": 5, \
...        "Entre 10 y 20 horas": 15, \
...        "Entre 20 y 40 horas": 30, \
...        "Más de 40 horas": 50}
>>> d['hrsNum'] = [hrs.get(v, NaN) for v in d.hrsTrabajo]
>>> d.CF1op.corr(d.hrsNum)
-0.13138744351929607

Más que trabajes, peor te va, pero no gravemente (correlación negativa leve); 
convendría graficar esto en un scatterplot en una práctica futura.

Habíamos brincado la parte de cuántos puntos sacaron en el examen de ingreso a la facu.
Vamos a examinar eso ahora antes de que se nos vuelva a olvidar.

In [ ]:
>>> d.examenIng.unique()
array([ 'No recuerdo la calificación cuando hice mi horario fui de los primeros entonces quiere decir me fue bien ',
       'realmente no recuerdo la puntuación',
       'recuerdo que conteste facilmente todo el examen',
       'En el examen dónde se me dificulto fue pensamiento analitico', nan,
       '400',
       'Nunca pregunte un resultado de puntos en si  pero no se me complico casi nada el examen salvo por ingles ',
       'recuerdo que gente salía llorando del slón',
       'recuerdo gente salir llorando del salón', 'no se ',
       'no recuerdo ningun resultado  pero al hacer el examen me senti conforme',
       'No me fue dado el puntaje pero estuve dentro de los 10 mejores puntajes de la generación',
       'No se cuantos puntos obtuve pero me invitaron a algo de intercambios al inicio de mi primer semestre',
       'No recuerdo', 'No me lo dieron.', 'recuerdo que fue sencillo',
       'No recuerdo pero fue alta porque pude elegir el mejor horario',
        ...

Nope. Olvidemos de eso. Esto no va a pasar. Nadie se acuerda nada coherente.
Estadística descriptiva básica no nos ayudará aquí.

Quizá estén más enterados sobre su promedio actual en la FIME:

In [ ]:
>>> d.promActual.unique()
array([nan, '80', '75-80', '85', '80-85', '78', '77', '70-80', '81', '75',
       '86.5', '82', '87.5', '83', '92', '70', '84', '82.6', '80.57',
       '76-79', '86'], dtype=object)
>>> d.promActual.value_counts()
80       7
78       4
85       3
80-85    3
75-80    3
81       2
84       2
82       2
80.57    1
87.5     1
92       1
70       1
82.6     1
83       1
75       1
86       1
76-79    1
86.5     1
70-80    1
77       1
Name: promActual, dtype: int64

Mejor, mucho mejor. Algunos más precisos que otros, pero se pueden arreglar.
Lo malo es que son bien pocos los que saben su promedio.

En vez de intentar a relacionar el promedio con la calificación final, 
mejor intentemos relacionar el sí o no saben su promedio con su resultado:

In [ ]:
>>> d['sabePromedio'] =  [v != 'nan' for v in [str(v) for v in d.promActual]]
>>> for sp in d.sabePromedio.unique():
...     print("sabe su promedio", sp)
...     print(d.loc[d.sabePromedio == sp]['CF1op'].mean())
...     print(d.loc[d.sabePromedio == sp]['CF2op'].mean())
... 
sabe su promedio False
62.68359375
71.1857142857
sabe su promedio True
nan
nan
>>> d.sabePromedio.value_counts()
False    984
True      38
Name: sabePromedio, dtype: int64

Pues, ni modo, no conocemos el resultado de nadie que haya reportado su promedio. 
Habrá que conseguir resultados de Sara y/o Blanca para prácticas futuras.

Chequemos lo de sí o no saben cuántos créditos da la unidad de aprendizaje y 
cuántas horas de estudio es cada crédito.

In [ ]:
>>> d.creditos.unique()
array([nan, 'No sé.', 'Tres.', 'Dos.', 'Cuatro.', '10', '20', '40', 'Uno.',
       '30'], dtype=object)
>>> d.creditos.value_counts()
No sé.     290
Cuatro.    116
Dos.        91
Tres.       80
Uno.         6
Cinco.       2
10           1
5 horas      1
Name: creditos, dtype: int64
>>> d.corr.unique()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'function' object has no attribute 'unique'
>>> d['corr'].unique()
array([nan, '60', 'No sé.', 'busqueda de informacion',
       'Resolviendo los examenes', '30',
       'por medio de la página web de la maestra, haciendo operaciones.',
       'Leer y practicar',
       'repasar apuntes, buscar videos relacionados a la clase', '20',
       'Grupos de estudio', '10',
       ...

Lo de "corr" no se puede llamar igual que a créditos porque existe una rutina para data frames en pandas que se llama corr; la notación rollosa funciona, sin embargo.

Es evidente que otra vez hay datos que no estén bien: 
las respuestas de la pregunta de con cuáles técnicas estudiaron
invaden la columna de cuántas horas es un crédito.   

A ver la hoja de cálculo manualmente otra vez.
Como antes, los semestres viejos tenían una columna de comentarios que no se había agregado en los datos de AD18, lo que causó que se desalinearan los datos.
Nada que una corrida más de combina.py no pueda arreglar..

In [ ]:
>>> d['corr'].unique()
array([nan, '60', 'No sé.', '30', '20', '10', '120', '40', '50', '1:30',
       '100'], dtype=object)
>>> d['corr'].value_counts()
No sé.    408
30         94
10         40
20         20
40          7
50          6
120         5
60          3
1:30        1
100         1
Name: corr, dtype: int64

Un vistazo rápido al sitio web de la FIME confirma que las unidades de aprendizaje con todos de tres créditos,
mientras el modelo educativo de licenciatura de la UANL aclara que "[s]e utiliza como convención que un crédito UANL es equivalente a 30 horas de trabajo del estudiante".

Vamos a ver si a los que saben estas dos cosas les va mejor que a los demás:

In [ ]:
>>> sabeCreditos = d.loc[d.creditos == 'Tres.']
>>> sabeHoras = d.loc[d['corr'] == '30']
>>> len(sabeCreditos)
80
>>> len(sabeHoras)
94
>>> sabeAmbos = sabeCreditos.loc[d['corr'] == '30']
>>> len(sabeAmbos)
12
>>> sabeAmbos.CF1op.mean()
77.63636363636364
>>> sabeAmbos.CF2op.mean()
74.0
>>> sabeHoras.CF1op.mean()
76.476190476190482
>>> sabeHoras.CF2op.mean()
69.666666666666671
>>> sabeCreditos.CF1op.mean()
73.553846153846152
>>> sabeCreditos.CF2op.mean()
74.909090909090907
>>> noSabeCreditos = d.loc[d.creditos != "Tres."]
>>> noSabeHoras = d.loc[d['corr'] != '30']
>>> noSabeNinguno = noSabeCreditos.loc[d['corr'] != '30']
>>> noSabeHoras.CF1op.mean()
62.093686354378818
>>> noSabeHoras.CF2op.mean()
71.253731343283576
>>> noSabeCreditos.CF1op.mean()
61.102908277404921
>>> noSabeCreditos.CF2op.mean()
70.491525423728817
>>> noSabeNinguno.CF1op.mean()
60.78032036613272
>>> noSabeNinguno.CF2op.mean()
70.596491228070178

Aquí también ocupamos pruebas estadísticas, pero sí punta que los que saben ambas cosas suelen sacar mejores calificaciones, mientras los que no saben ninguno de esos dos datos son que peores calificaciones sacan.

Quizá refleja un desinterés general en sus estudios.

También aún queda pendiente analizar qué calificación dicen que esperan obtener,
algo que se pregunta en las tres encuestas.

In [ ]:
>>> for ce in ['_ini', '_mcu', '']: # el que no tiene nada es el ordinario                                                                      
...     variante = 'califEsp' + ce
...     print(variante)
...     for c in d.caso.unique():
...         print(c, "\n", d.loc[d.caso == c][variante].value_counts(sort=False, normalize=True, dropna=True))
... 
califEsp_ini
nan 
 Series([], Name: califEsp_ini, dtype: float64)
1ra 
 80-89     0.479638
90-100    0.461538
70-79     0.058824
Name: califEsp_ini, dtype: float64
2da 
 80-89     0.666667
90-100    0.266667
70-79     0.066667
Name: califEsp_ini, dtype: float64
3ra 
 70-79     0.166667
90-100    0.111111
80-89     0.722222
Name: califEsp_ini, dtype: float64
califEsp_mcu
nan 
 Series([], Name: califEsp_mcu, dtype: float64)
1ra 
 2da                                      0.004878
Estimo aprobar en segunda oportunidad    0.009756
80-89                                    0.443902
90-100                                   0.112195
70-79                                    0.429268
Name: califEsp_mcu, dtype: float64
2da 
 80-89     0.108108
90-100    0.027027
2da       0.081081
70-79     0.783784
Name: califEsp_mcu, dtype: float64
3ra 
 2da      0.230769
70-79    0.769231
Name: califEsp_mcu, dtype: float64
califEsp
nan 
 Series([], Name: califEsp, dtype: float64)
1ra 
 Creo que aprobaré en segunda oportunidad    0.005348
2da                                         0.016043
80-89                                       0.336898
90-100                                      0.106952
70-79                                       0.534759
Name: califEsp, dtype: float64
2da 
 80-89     0.147059
2da       0.058824
90-100    0.029412
70-79     0.735294
3ra       0.029412
Name: califEsp, dtype: float64
3ra 
 2da      0.111111
70-79    0.888889
Name: califEsp, dtype: float64

Los que van a terceran son los menos propensos en estimar que saquen encima de 90 al inicio del semestre.
A medio curso, los que pasarán en primera ya saben que van a pasar
(menos de un porciento piensa que tendrá segundas), 
mientras entre los que irán a terceras, una cuarta parte ya espera estar en segundas.

Ahora da ganas de checar correlaciones. 
Vamos a representar cada intervalo con su punto medio: 
* 79-79 valdrá 75
* 80-89 valdrá 85
* 90-100 valdrá 95
* segundas valdrán 50
* al parecer nadie selecciona la opción "No creo aprobar en este semestre", por lo cual no ocupa tener un valor

y luego calculo la correlación entre la calificación de primera oportunidad, si es que existe, con los tres estimados: inicio de semestre, medio curso y final del semestre.

In [ ]:
>>> valores = {'70-79': 75, '80-89': 85, '90-100': 95, 'segunda': 50}
>>> d.califEsp = d.califEsp.replace("Creo que aprobaré en segunda oportunidad", "segunda")
>>> d.califEsp_ini = d.califEsp_ini.replace("Estimo aprobar en segunda oportunidad", "segunda")
>>> d.califEsp_mcu = d.califEsp_mcu.replace("Estimo aprobar en segunda oportunidad", "segunda")
>>> d['eI'] = [valores.get(v, NaN) for v in d.califEsp_ini]
>>> d['eM'] = [valores.get(v, NaN) for v in d.califEsp_mcu]
>>> d['eF'] = [valores.get(v, NaN) for v in d.califEsp]
>>> d.CF1op.corr(d.eI)
0.1957813659194152
>>> d.CF1op.corr(d.eM)
0.4724877223145954
>>> d.CF1op.corr(d.eF)
0.45281735470132939

Al parecer el poder estudiantil de pronósticar su calificación final es muy bajo al inicio del semestre, se fortalece bastante después de presentar el examen de medio curso (y conocer su resultado), y luego baja un poco al final del semestre justo antes de presentar el examen ordinario.

Nos falta por analizar lo de asesorías y mecanismos de apoyo. 

In [ ]:
>>> d.asesorias.unique()
array([nan, 'No', 'Sí', 'Dos veces', 'Una vez', 'Tres veces'], dtype=object)
>>> d.asesorias.value_counts()
No            298
Sí             50
Una vez        11
Dos veces       3
Tres veces      1
Name: asesorias, dtype: int64
>>> d['fueAses'] = ["NA" if v is NaN else False if str(v) == "No" else True for v in d.asesorias]
>>> d.fueAses.value_counts()
NA       659
False    298
True      65
Name: fueAses, dtype: int64
>>> print(d.loc[d.fueAses == True]['CF1op'].mean())
78.35
>>> print(d.loc[d.fueAses == False]['CF1op'].mean())
73.3695652174
>>> print(d.loc[d.fueAses == "NA"]['CF1op'].mean())
55.2824675325

Esto sí es interesante. Los que fueron a asesorías, desempeñaron mejor. 
Los que dijeron que no fueron, segundoi mejor.
Los que ni contestaron la pregunta, apestaron en primera oportunidad. 
Está empezando a dar el aire que el falta de interés y esfuerzo es una causa de reprobación.
(Surprise, surprise.)
Habrá que hacer pruebas estadísticas en prácticas futuras.

Vamos a ver qué podemos concluir a partir de si dicen que ocuparán reforzar temas en el futuro:

In [ ]:
>>> for t in d.temas.unique():
...     print(t)
...     print(d.loc[d.temas == t]['CF1op'].mean())
...     print(d.loc[d.temas == t]['CF2op'].mean())
... 
nan
nan
nan
Unos pocos.
74.5942028986
73.4347826087
Bastantes.
72.1348314607
72.4666666667
Creo tener que estudiarlos todos luego.
76.7916666667
72.75
Ninguno.
81.3333333333
nan
todos los temas
nan
nan
Solo continuar ampliando 
100.0
nan
hacer mas facil el examen
61.0
70.0
>>> ok = d.loc[d.temas == "Ninguno."]['CF1op']
>>> ok.describe()
count      3.000000
mean      81.333333
std       16.196707
min       71.000000
25%       72.000000
50%       73.000000
75%       86.500000
max      100.000000
Name: CF1op, dtype: float64

Los que *no* sienten que les falte algo por reforzar, sacan en promedio más de 80. 
Fueron solamente tres personas, pero todos sí pasaron en primera oportunidad.

¿Qué tal si les falta reforzar temas en general?

In [ ]:
>>> d.temasGral.unique()
array([nan,
       'Programación avanzada;Redacción de textos técnicos en español;Redacción de textos técnicos en inglés',
       'Trigonometría;Álgebra;Cálculo diferencial;Cálculo integral;Vectores y matrices (álgebra lineal);Programación avanzada',
       'Cálculo integral;Programación básica;Programación avanzada;Redacción de textos técnicos en inglés',
       'Cálculo diferencial', 'Programación básica;Programación avanzada',
       'Cálculo integral;Programación básica;Programación avanzada',
       'Cálculo diferencial;Programación avanzada',
       'Programación avanzada', 'Cálculo integral',
       'Trigonometría;Probabilidad y estadística;Programación básica;Programación avanzada',
        ...

Eh... Mejor por el momento contemos cuántas temas marcó cada quien:
si el string tiene largo mayor a uno, el número de temas seleccionados
es la cantidad de ; más uno:

In [ ]:
d['cuantasTemas'] = [0 if len(t) < 1 else t.count(';') + 1 for t in [str(v) if v is not NaN else '' for v in d.temasGral]]
>>> d.CF1op.corr(d.cuantasTemas)
0.32525947834350188

Según esto, gente que saca mejores calificaciones suele reconocer más temas como áreas que ocupan refuerzo.
Otra vez se necesita una prueba estadística antes de lanzarse a conclusiones.

Haremos lo mismo con las formas de apoyo y medios por lo cuales obtener apoyo, para concluir por hoy.

In [ ]:
>>> d['formasApoyo'] = [0 if len(t) < 1 else t.count(';') + 1 for t in [str(v) if v is not NaN else '' for v in d.apoyo]]
>>> d['cuantosMedios'] = [0 if len(t) < 1 else t.count(';') + 1 for t in [str(v) if v is not NaN else '' for v in d.medios]]
>>> d.CF1op.corr(d.formasApoyo)
0.38389848090645728
>>> d.CF1op.corr(d.cuantosMedios)
0.35012981268365978

Pasa lo mismo: a los que mejor les va en la primera oportunidad, más les interesan las formas y medios de apoyo.

En el tercer reporte, saca algo parecido con tus datos: conteos, promedios, unas cuantas correlaciones, junto con limpieza, categorización y cuantificación de la información. Aún no es necesario graficar ni realizar pruebas estadísticas; habrá prácticas futuras dedicadas a ambos aspectos.